In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('spam.csv',encoding='latin-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
data.dropna(axis=1,inplace=True)
data.columns = ['label','message']

In [4]:
data.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
#unique labels
data.label.unique()

array(['ham', 'spam'], dtype=object)

In [6]:
data.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [7]:
data['label_num'] = data.label.map({'ham':0,'spam':1})

In [8]:
data.head()

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [9]:
x_ham = data[data.label_num == 0].message
x_spam = data[data.label_num == 1].message

In [10]:
x_ham[:5]

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
6    Even my brother is not like to speak with me. ...
Name: message, dtype: object

In [12]:
x = data.message
y = data.label_num

In [13]:
y.shape

(5572,)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=5)

In [15]:
x_train[:5]

2960    I'm doing da intro covers energy trends n pros...
3549    Dad wanted to talk about the apartment so I go...
3813                       Can. Dunno wat to get 4 her...
4373    K and you're sure I don't have to have consent...
1660           No just send to you. Bec you in temple na.
Name: message, dtype: object

In [29]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
vect = CountVectorizer()

In [17]:
vect.fit(x_train)
x_train_dtm =vect.transform(x_train)

In [18]:
x_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
x_test_dtm = vect.transform(x_test)

In [20]:
x_test_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [22]:
nb.fit(x_train_dtm,y_train)
y_pred = nb.predict(x_test_dtm)

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [24]:
accuracy_score(y_test,y_pred)

0.990667623833453

In [25]:
confusion_matrix(y_test,y_pred)

array([[1223,    2],
       [  11,  157]], dtype=int64)

In [26]:
#False positive 
x_test[(y_test==0) & (y_pred ==1)]

4380               Mathews or tait or edwards or anderson
4727    I (Career Tel) have added u as a contact on IN...
Name: message, dtype: object

In [27]:
#false Negative
fn = list(x_test[(y_test == 1) & (y_pred == 0)])

In [28]:
nb.predict_proba(x_test_dtm)

array([[9.99814315e-01, 1.85684587e-04],
       [9.99998040e-01, 1.96019345e-06],
       [1.00000000e+00, 1.69708567e-12],
       ...,
       [9.99999392e-01, 6.08234736e-07],
       [9.99249849e-01, 7.50151106e-04],
       [7.94262563e-21, 1.00000000e+00]])

In [30]:
vect_tf = TfidfVectorizer()
vect_tf.fit(x_train)

TfidfVectorizer()

In [31]:
x_train_dtm_2 = vect_tf.transform(x_train)

In [32]:
x_train_dtm_2.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
x_test_dtm_2 = vect_tf.transform(x_test)

In [34]:
nb = MultinomialNB()
nb.fit(x_train_dtm_2,y_train)

MultinomialNB()

In [35]:
y_pred_2= nb.predict(x_test_dtm_2)

In [36]:
accuracy_score(y_test,y_pred_2)

0.9662598707824839